# Generated by Django 2.2.2 on 2020-03-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20200303_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumento',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'violao'), (2, 'piano'), (3, 'cajon')]),
        ),
    ]
