# Generated by Django 2.2.2 on 2020-03-04 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_auto_20200303_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumento',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instrumentos', to='crud.Loja'),
        ),
    ]
